- name: update apt 
  apt:
    update_cache: yes

- name: Copy file with owner and permissions
  copy:
    src: ../../../Kubernetes
    dest: /home/ubuntu/
    owner: ubuntu
    group: ubuntu


- name: change owner for directory 
  file:
    path:  /home/ubuntu/jenkins
    recurse: yes
    owner: ubuntu
    group: ubuntu
    state: directory


- name: install kubernetes package
  pip:
    name: kubernetes

- name: Create a Deployment by reading the definition from a local file
  become: false
  kubernetes.core.k8s:
    state: present
    src: "{{ item }}"
  loop:
    "{{ JenkinsFiles }}"

  