apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
  annotations: 
      service.beta.kubernetes.io/aws-load-balancer-type: application 
spec:
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
